### ISSUE TITLE
Docs functional test R11 (1.2) Checklist

### ISSUE THREAD

**Issue by zxyanliu** [MicrosoftDocs/composer-docs#35]
Composer version: [v1.1.1-nightly.181539.5e9576e](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181539.5e9576e)
## Quickstart 
  - [x] [composer-quickstart-create-bot.md](https://docs.microsoft.com/en-us/composer/quickstart-create-bot) 
## Publish 
  - [ ] [how-to-publish-bot.md](https://docs.microsoft.com/en-us/composer/how-to-publish-bot) 
     - [x] provisioning new Azure resources and publish to Azure Web App
     - [x] publish to Azure Web App to exisiting Azure resources
     - [ ] publish to Auzre Functions
## Tutorials
  - [x] [tutorial/tutorial-create-bot.md](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-create-bot) / [v1.1.1-nightly.181088.77ad8e1](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181088.77ad8e1)
  - [x] [tutorial/tutorial-add-dialog.md](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-add-dialog) (https://github.com/microsoft/BotFramework-Composer/issues/4658) / [v1.1.1-nightly.181088.77ad8e1](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181088.77ad8e1)
  - [x] [tutorial/tutorial-get-weather.md](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-get-weather)  / [v1.1.1-nightly.181539.5e9576e](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181539.5e9576e)
  - [x] [tutorial/tutorial-add-help.md](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-add-help) / [v1.1.1-nightly.181539.5e9576e](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181539.5e9576e)
  - [x] [tutorial/tutorial-lg.md](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-lg) /[v1.1.1-nightly.181539.5e9576e](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181539.5e9576e)
  - [x] [tutorial/tutorial-cards.md](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-cards) / [v1.1.1-nightly.181539.5e9576e](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181539.5e9576e)
  - [ ] [tutorial/tutorial-luis.md](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis) / [v1.1.1-nightly.181539.5e9576e](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181539.5e9576e) [Bug with v1.1.1-nightly.183199.7a9bfc5](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.183199.7a9bfc5)
## Develop 
  - [x] [how-to-add-luis.md](https://docs.microsoft.com/en-us/composer/how-to-add-luis)
  - [x] [how-to-add-qna.md](https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot)
  - [x] [how-to-create-qna-kb.md](https://docs.microsoft.com/en-us/composer/how-to-create-qna-kb)
  - [x] [how-to-multiple-language.md](https://docs.microsoft.com/en-us/composer/how-to-use-multiple-language) 
  - [x] [how-to-use-oauth.md](https://docs.microsoft.com/en-us/composer/how-to-use-oauth)
  - [x] [how-to-send-http-request.md](https://docs.microsoft.com/en-us/composer/how-to-send-http-request)
  - [x] [how-to-connect-to-a-skill.md](https://docs.microsoft.com/en-us/composer/how-to-connect-to-a-skill) 
    - [x] Export a skill 
    - [x] Connect to a local skill 
    - [x] Connect to a remote skill
  - [x] [how-to-add-custom-action.md](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action)
