### ISSUE TITLE
Docs checklist

### ISSUE THREAD

**Issue by zxyanliu** [MicrosoftDocs/composer-docs#41]
- **Overview**
  - [x] introduction.md _[Needs revisit]_
  - [ ] what-is-new.md _[Needs create]_
- **Set up**
  - [x] setup-yarn.md
- **QuickStart**
  - [x] composer-onboarding.md
  - [x] composer-quickstart-create-bot.md
- **Tutorials**
  - [x] tutorial/tutorial-introduction.md 
  - [x] tutorial/tutorial-create-bot.md
  - [x] tutorial/tutorial-add-dialog.md
  - [x] tutorial/tutorial-get-weather.md 
  - [x] tutorial/tutorial-add-help.md 
  - [x] tutorial/tutorial-lg.md 
  - [x] tutorial/tutorial-cards.md 
  - [x] tutorial/tutorial-luis.md
- **Concepts**
  - [x] concept-dialog.md
  - [x] concept-events-and-triggers.md 
  - [x] concept-memory.md _[Needs revisit]_
  - [x] concept-natural-language-processing.md 
  - [x] concept-language-generation.md
  - [x] concept-language-understanding.md
  - [x] concept-best-practices.md
  - [x] concept-plugin.md
- **Samples**
  - [x] how-to-use-samples.md
- **Develop**
  - [x] how-to-send-messages.md
  - [x] how-to-send-cards.md
  - [x] how-to-ask-for-user-input.md
  - [x] how-to-control-conversation-flow.md 
  - [x] how-to-use-LUIS.md
  - [x] how-to-author-qna-kb.md  
  - [x] how-to-add-qna-to-bot.md
  - [x] how-to-define-triggers.md
  - [x] how-to-define-advanced-intents-entities.md 
  - [x] how-to-use-oauth.md
  - [x] how-to-send-http-request.md
  - [x] how-to-connect-to-a-skill.md
  - [x] how-to-add-custom-action.md
  - [x] how-to-use-plugin.md
  - [x] how-to-host-composer.md
  - [x] how-to-use-multiple-language.md
- **Debug**
  - [x] how-to-validate.md  
  - [x] how-to-capture-telemetry.md
- **Publish**
  - [x] how-to-publish-bot.md  
- **Resources**
  - [ ] Composer + PVA integration
