### ISSUE TITLE
R11 (1.2) Composer docs release checklist

### ISSUE THREAD

**Issue by zxyanliu** [MicrosoftDocs/composer-docs#46]
## 1. Prerelease functional tests [#35] 
@zxyanliu 
Composer versions: 
- [v1.1.1-nightly.181539.5e9576e](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181539.5e9576e)
- [v1.1.1-nightly.181088.77ad8e1](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181088.77ad8e1)
-  [v1.1.1-nightly.183199.7a9bfc5](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.183199.7a9bfc5)
- [v1.1.1-nightly.184169.f22adeb](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.184169.f22adeb) - most recent
### Quickstart 
  - [x] [composer-quickstart-create-bot.md](https://docs.microsoft.com/en-us/composer/quickstart-create-bot) 
### Tutorials
  - [x] [tutorial/tutorial-create-bot.md](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-create-bot) / [v1.1.1-nightly.181088.77ad8e1](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181088.77ad8e1)
  - [x] [tutorial/tutorial-add-dialog.md](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-add-dialog) (https://github.com/microsoft/BotFramework-Composer/issues/4658) / [v1.1.1-nightly.181088.77ad8e1](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181088.77ad8e1)
  - [x] [tutorial/tutorial-get-weather.md](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-get-weather)  / [v1.1.1-nightly.181539.5e9576e](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181539.5e9576e)
  - [x] [tutorial/tutorial-add-help.md](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-add-help) / [v1.1.1-nightly.181539.5e9576e](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181539.5e9576e)
  - [x] [tutorial/tutorial-lg.md](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-lg) /[v1.1.1-nightly.181539.5e9576e](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181539.5e9576e)
  - [x] [tutorial/tutorial-cards.md](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-cards) / [v1.1.1-nightly.181539.5e9576e](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181539.5e9576e)
  - [x] [tutorial/tutorial-luis.md](https://docs.microsoft.com/en-us/composer/tutorial/tutorial-luis) / [v1.1.1-nightly.181539.5e9576e](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.181539.5e9576e) / [Bug with v1.1.1-nightly.183199.7a9bfc5](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.183199.7a9bfc5)
## Develop 
  - [x] [how-to-add-luis.md](https://docs.microsoft.com/en-us/composer/how-to-add-luis)
  - [x] [how-to-add-qna.md](https://docs.microsoft.com/en-us/composer/how-to-add-qna-to-bot)
  - [x] [how-to-create-qna-kb.md](https://docs.microsoft.com/en-us/composer/how-to-create-qna-kb) [bug with v1.1.1-nightly.184169.f22adeb](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.184169.f22adeb)
  - [x] [how-to-multiple-language.md](https://docs.microsoft.com/en-us/composer/how-to-use-multiple-language) 
  - [x] [how-to-use-oauth.md](https://docs.microsoft.com/en-us/composer/how-to-use-oauth)
  - [x] [how-to-send-http-request.md](https://docs.microsoft.com/en-us/composer/how-to-send-http-request)
  - [x] [how-to-connect-to-a-skill.md](https://docs.microsoft.com/en-us/composer/how-to-connect-to-a-skill) 
    - [x] Export a skill 
    - [x] Connect to a local skill 
    - [x] Connect to a remote skill
  - [x] [how-to-add-custom-action.md](https://docs.microsoft.com/en-us/composer/how-to-add-custom-action) 
### Publish 
  - [x] [how-to-publish-bot.md](https://docs.microsoft.com/en-us/composer/how-to-publish-bot) 
     - [x] provisioning new Azure resources and publish to Azure Web App
     - [x] publish to Azure Web App to existing Azure resources
     - [x] publish to Auzre Functions
## 2. Prerelease docs updates [#41] 
- **Overview**
  - [x] introduction.md _[Needs revisit]_ @zxyanliu 
  - [ ] what-is-new.md _[Needs creation]_ @zxyanliu 
- **Install**
  - [x] install-composer.md @zxyanliu 
- **QuickStart**
  - [x] composer-onboarding.md @zxyanliu 
  - [x] composer-quickstart-create-bot.md @zxyanliu 
- **Tutorials**
  - [x] tutorial/tutorial-introduction.md 
  - [x] tutorial/tutorial-create-bot.md @mmiele 
  - [x] tutorial/tutorial-add-dialog.md @mmiele 
  - [x] tutorial/tutorial-get-weather.md @mmiele 
  - [x] tutorial/tutorial-add-help.md @mmiele 
  - [x] tutorial/tutorial-lg.md @zxyanliu 
  - [x] tutorial/tutorial-cards.md @zxyanliu 
  - [x] tutorial/tutorial-luis.md @zxyanliu 
- **Concepts**
  - [x] concept-dialog.md @zxyanliu 
  - [x] concept-events-and-triggers.md @zxyanliu 
  - [x] concept-memory.md _[Needs revisit]_ @zxyanliu 
  - [x] concept-natural-language-processing.md @zxyanliu 
  - [x] concept-language-generation.md @zxyanliu 
  - [x] concept-language-understanding.md @zxyanliu 
  - [x] concept-best-practices.md @zxyanliu 
  - [x] concept-plugin.md @zxyanliu 
- **Samples**
  - [x] how-to-use-samples.md @zxyanliu 
- **Develop**
  - [x] how-to-send-messages.md @zxyanliu 
  - [x] how-to-send-cards.md @zxyanliu 
  - [x] how-to-ask-for-user-input.md @zxyanliu 
  - [x] how-to-control-conversation-flow.md  @zxyanliu 
  - [x] how-to-use-LUIS.md @zxyanliu 
  - [x] how-to-create-qna-kb.md @zxyanliu [bug with v1.1.1-nightly.184169.f22adeb](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v1.1.1-nightly.184169.f22adeb) - most recent]
  - [x] how-to-add-qna-to-bot.md @zxyanliu 
  - [x] how-to-define-triggers.md @zxyanliu 
  - [x] how-to-define-advanced-intents-entities.md @zxyanliu 
  - [x] how-to-use-oauth.md @zxyanliu 
  - [x] how-to-send-http-request.md @zxyanliu 
  - [x] how-to-connect-to-a-skill.md @zxyanliu 
  - [x] how-to-add-custom-action.md @zxyanliu 
  - [x] how-to-use-plugin.md @zxyanliu 
  - [x] how-to-host-composer.md @zxyanliu 
  - [x] how-to-use-multiple-language.md @zxyanliu 
- **Debug**
  - [x] how-to-validate.md @zxyanliu 
  - [x] how-to-capture-telemetry.md @zxyanliu 
- **Publish**
  - [x] how-to-publish-bot.md  @zxyanliu 
- **Resources**
  - [ ] Composer + PVA integration @emgrol 
## 4. Update docs release dates pointing to Composer release date [#43] @zxyanliu
